# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gghT1qIx3CVbN2Qkm3U264MJTkKpXW1r
"""



"""# Новый раздел"""

import pandas as pd
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

print(df)

print(df[(0<df['population']) & (df['population']<500)]['median_house_value'].mean())

print(df[df['population']==df['population'].min()]['households'].max())